### PR TITLE
Make sure PRs have seed data

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR introduces automation for seeding developer user data into the database. This is needed in order to allow future PRs (and only PRs) to have information pre-populated in the database so that we can quickly demonstrate functionality that now depends on there being data inside the db.

**Other Changes**
- Fix the logout url location behavior so that it points back to the proper top level path
- Relocate admin components into separate folder
- Standardize Keycloak environment secret object names in openshift
- Remove parallelization in Jenkins test stage

[SHOWCASE-916](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-916)

## Types of changes

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-k8vopl-tools.pathfinder.gov.bc.ca/dashboard?id=nr-get-token-pr-158

**Comment by TimCsaky** [comment]
can the database be seeded in a local dev environment by running npm run seed:dev ?

**Comment by jujaga** [comment]
> 
> 
> can the database be seeded in a local dev environment by running npm run seed:dev ?

Yes that is the intent and some documentation has been added to note that capability.

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-k8vopl-tools.pathfinder.gov.bc.ca/dashboard?id=nr-get-token-pr-158

**Pull request merged**
