### PR TITLE
Add Vuex to Frontend and minor bugfixes

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR adds vuex and an empty store to the baseline frontend framework.
Other fixes:
* Change auth button to white outlined style
* Change router to force redirect to /home instead of aliasing as /
* Reduce specificity of navbar path highlighting
* Fix axios $httpApi baseURL misconfiguration

[SHOWCASE-761](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-761)

## Types of changes

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-k8vopl-tools.pathfinder.gov.bc.ca/dashboard?id=nr-get-token-pr-130

**Comment by jujaga** [comment]
> 
> 
> Looks good.
> Quick question and hopefully it can be fixed here, or we create a new ticket...
> The loading/spinner, I see a blue line at the top of the screen, and the spinner circle is over the login/logout button. I think that is supposed to be under the nav bar and in the main content body? Take a look and see what's up.

That visual behavior is from the NProgress npm package (which isn't very configurable). It was put in as part of the skeleton as just a subtle visual cue that something on the page is currently loading. I know Vuetify has progress bar equivalents so we may eventually migrate to using a Vuetify loading construct instead of this.

**Comment by parc-jason** [comment]
> > Looks good.
> > Quick question and hopefully it can be fixed here, or we create a new ticket...
> > The loading/spinner, I see a blue line at the top of the screen, and the spinner circle is over the login/logout button. I think that is supposed to be under the nav bar and in the main content body? Take a look and see what's up.
> 
> That visual behavior is from the NProgress npm package (which isn't very configurable). It was put in as part of the skeleton as just a subtle visual cue that something on the page is currently loading. I know Vuetify has progress bar equivalents so we may eventually migrate to using a Vuetify loading construct instead of this.

OK, well, I think it should go, even from the skeleton, because it doesn't really provide a visual clue - it's tough to see.  So, if it's not going to be made better, then we should remove it.  If it can get placed below the nav bar and over the content, then it is worthwhile.

**Comment by loneil** [comment]
@parc-jason @jujaga lets leave it in and merge this PR so I can get the changes into my branch. Yeah we'll definitely not leave it where it is (and we'll look at the native Vuetify option as well)

**Comment by parc-jason** [comment]
> @parc-jason @jujaga lets leave it in and merge this PR so I can get the changes into my branch. Yeah we'll definitely not leave it where it is (and we'll look at the native Vuetify option as well)

Sounds good.

**Pull request merged**
