### PR TITLE
Add permissions step and registration button

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR adds a GETOK application acronym registration button and surrounding step flow to ensure compliance.

This adds an interim flow to allow users to know how to get acronym approval permissions.

[SHOWCASE-194](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-194)

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-k8vopl-tools.pathfinder.gov.bc.ca/dashboard?id=nr-get-token-pr-69

**Comment by matthewhall78** [comment]
I sent an email requesting access to MSSC.  Looks like the process works. But we will need to monitor our email address closely.

**Comment by matthewhall78** [comment]
I notice now that code coverage dropped. Let's make sure from now on that with each PR the code coverage goes up.

**Comment by parc-jason** [comment]
Maybe we can add a filter to the common services email for getok messages to forward to all of us?
Or create a mailing list ?

**Comment by bcgov-nr-csst** [comment]
I created an email Rule that will forward emails with the Subject containing: “GETOK Registration” to you 3 devs

**Pull request merged**
